### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by jcs090218** [flymake/emacs-flymake-cursor#5]
Hi, Is there a maintainer for this package? I would like to maintain this package if there is no one maintaining it! :D

@illusori

**Comment by illusori** [comment]
I handed over maintenance to @ryoung786 five years ago or so. I'm not sure if they're still actively interested in maintaining. I'll add you to the github org, but I don't think I can grant permissions to publish to marmalade anymore.

I don't use flymake anymore, I've moved over to flycheck which was designed from the ground up in a much more sensible manner than flymake.

**Comment by jcs090218** [comment]
> I'll add you to the github org, but I don't think I can grant permissions to publish to marmalade anymore.

Thank you! :)

> I don't use flymake anymore, I've moved over to flycheck which was designed from the ground up in a much more sensible manner than flymake.

That's so sad to hear! I use both `flycheck` and `flymake` and I really appreciate what both software bring me. It would definitely be great to keep this software actively maintain.

**Comment by illusori** [comment]
Well you have my complete blessing. Flymake was abandoned when I adopted it, so I'm glad to let someone else do the same!
